# Generated by Django 5.1.1 on 2024-09-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Uniforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=70)),
                ('quantidade_estoque', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniforms.categorias')),
                ('tamanho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniforms.tamanhos')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_saida', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('data_saida', models.DateField()),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniforms.funcionario')),
                ('id_uniforme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniforms.uniforms')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nota', models.IntegerField()),
                ('data_emissao', models.DateField()),
                ('data_entrada', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('valor_uni', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('uniforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforms.uniforms')),
            ],
        ),
    ]
