# Generated by Django 5.1.1 on 2024-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0002_uniforms_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniforms',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
