# Generated by Django 5.1.1 on 2024-09-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0004_alter_entrada_num_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='CartTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforms.funcionario')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforms.uniforms')),
            ],
        ),
    ]
