# Generated by Django 5.1.1 on 2024-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforms', '0005_alter_funcionario_nome_carttemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='data_saida',
            field=models.DateTimeField(),
        ),
    ]
